//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace CSharpFeatures.Data
{
    public partial class AppDemoEntities : ObjectContext
    {
        public const string ConnectionString = "name=AppDemoEntities";
        public const string ContainerName = "AppDemoEntities";
    
        #region Constructors
    
        public AppDemoEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public AppDemoEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public AppDemoEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Sue> Sues
        {
            get { return _sues  ?? (_sues = CreateObjectSet<Sue>("Sues")); }
        }
        private ObjectSet<Sue> _sues;
    
        public ObjectSet<SueType> SueTypes
        {
            get { return _sueTypes  ?? (_sueTypes = CreateObjectSet<SueType>("SueTypes")); }
        }
        private ObjectSet<SueType> _sueTypes;

        #endregion

    }
}
