//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace CSharpFeatures.Data
{
    public partial class Sue
    {
        #region Primitive Properties
    
        public virtual System.Guid ID
        {
            get;
            set;
        }
    
        public virtual int SysVersion
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreatedOn
        {
            get;
            set;
        }
    
        public virtual string CreatedBy
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> UpdatedOn
        {
            get;
            set;
        }
    
        public virtual string UpdatedBy
        {
            get;
            set;
        }
    
        public virtual string SueCode
        {
            get;
            set;
        }
    
        public virtual string EnforceOrgan
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> RegisterDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DelayApplyDate
        {
            get;
            set;
        }
    
        public virtual string IsEnd
        {
            get;
            set;
        }
    
        public virtual string ConductResult
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> EndDate
        {
            get;
            set;
        }
    
        public virtual string PunishOpion
        {
            get;
            set;
        }
    
        public virtual string SueName
        {
            get;
            set;
        }
    
        public virtual string SueLevel
        {
            get;
            set;
        }
    
        public virtual string SuePosition
        {
            get;
            set;
        }
    
        public virtual string SueBigType
        {
            get;
            set;
        }
    
        public virtual string SueSmallType
        {
            get;
            set;
        }
    
        public virtual string SueSource
        {
            get;
            set;
        }
    
        public virtual string SueContent
        {
            get;
            set;
        }
    
        public virtual string SueReason
        {
            get;
            set;
        }
    
        public virtual string Reporter
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ReportDate
        {
            get;
            set;
        }
    
        public virtual string EnforcePersons
        {
            get;
            set;
        }
    
        public virtual string PartyName
        {
            get;
            set;
        }
    
        public virtual string PartyGender
        {
            get;
            set;
        }
    
        public virtual Nullable<int> PartyAge
        {
            get;
            set;
        }
    
        public virtual string PartyVocation
        {
            get;
            set;
        }
    
        public virtual string PartyTel
        {
            get;
            set;
        }
    
        public virtual string PartyCorporation
        {
            get;
            set;
        }
    
        public virtual string PartyPost
        {
            get;
            set;
        }
    
        public virtual string PartyAddr
        {
            get;
            set;
        }
    
        public virtual string RegisterCode
        {
            get;
            set;
        }
    
        public virtual string SuePunish
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> SueFine
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ConductDate
        {
            get;
            set;
        }
    
        public virtual string HotlineCaseCode
        {
            get;
            set;
        }
    
        public virtual string Longitude
        {
            get;
            set;
        }
    
        public virtual string Latitude
        {
            get;
            set;
        }
    
        public virtual Nullable<int> CoordinateType
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IsDelay
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> DelayDays
        {
            get;
            set;
        }
    
        public virtual string DelayApplyLoginName
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> IsDelayEnd
        {
            get;
            set;
        }
    
        public virtual string DecisionCode
        {
            get;
            set;
        }
    
        public virtual string ReceiptCode
        {
            get;
            set;
        }
    
        public virtual string PunishType
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreateDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual SueType SueType
        {
            get { return _sueType; }
            set
            {
                if (!ReferenceEquals(_sueType, value))
                {
                    var previousValue = _sueType;
                    _sueType = value;
                    FixupSueType(previousValue);
                }
            }
        }
        private SueType _sueType;

        #endregion
        #region Association Fixup
    
        private void FixupSueType(SueType previousValue)
        {
            if (previousValue != null && previousValue.Sues.Contains(this))
            {
                previousValue.Sues.Remove(this);
            }
    
            if (SueType != null)
            {
                if (!SueType.Sues.Contains(this))
                {
                    SueType.Sues.Add(this);
                }
            }
        }

        #endregion
    }
}
