//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.CommonCRUDService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CommonCRUDService.ICommonCRUDService")]
    public interface ICommonCRUDService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonCRUDService/Add", ReplyAction="http://tempuri.org/ICommonCRUDService/AddResponse")]
        void Add(WCFService.OuterLab.EntityBase entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommonCRUDServiceChannel : WCFClient.CommonCRUDService.ICommonCRUDService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommonCRUDServiceClient : System.ServiceModel.ClientBase<WCFClient.CommonCRUDService.ICommonCRUDService>, WCFClient.CommonCRUDService.ICommonCRUDService {
        
        public CommonCRUDServiceClient() {
        }
        
        public CommonCRUDServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommonCRUDServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonCRUDServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonCRUDServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Add(WCFService.OuterLab.EntityBase entity) {
            base.Channel.Add(entity);
        }
    }
}
