//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Concrete Entity : EntityBase
{
	protected override void OnValidate()
	{
		throw new System.NotImplementedException();
	}

	protected override void SetDefaultValue()
	{
		throw new System.NotImplementedException();
	}

}

