//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class EntityBase : IPersistableObject
{
	protected abstract void SetDefaultValue();

	protected abstract void OnValidate();

	private void IPersistableObject.SetDefaultValue()
	{
		throw new System.NotImplementedException();
	}

	private void IPersistableObject.OnValidate()
	{
		throw new System.NotImplementedException();
	}

}

